### ISSUE TITLE
Email disappearing into the ether

### ISSUE THREAD

**Issue by davisford** [sendgrid/nodemailer-sendgrid-transport#11]
I've been using nodemailer with this transport since December 2014, and it had been working very well until recently.  Last week sendgrid had a lot of outages, and things went downhill from there.  Once they reported the status was back up, things started working again *most of the time*.

What I'm seeing could better be explained in code.  Here's a function I wrote which sends an email.

```javascript
function sendEmail(pdfurl, data, template, callback) {
  log('Trying to send email to ', data, ' with attachment at ', pdfurl);

  email.sendTemplate(template,
    /* mail options */
    {
      from: email.formatAddress('SomeUser', 'no-reply@somedomain.com'),
      to: data.recipients,
      subject: 'Some Subject',
      attachments: [
        {
          filename: data.filename,
          contentType: 'application/pdf',
          contentEncoding: 'gzip',
          // we need hyperzip to handle gunzipping content
          // @see https://github.com/andris9/Nodemailer/issues/356
          content: hyperzip().request(pdfurl)
        }
      ]
    },
    /* locals */
    {
      name: data.sender,
      notes: data.notes,
      url: data.url,
      unsublink: data.unsublink
    },
    callback
  );
}
```

`error` and `log` just log to respective `stderr`, `stdout`.

The implementation of `sendTemplate` follows:

```javascript
exports.sendTemplate = function (templateName, data, context, cb) {
  log('prepare to render email template: %s ', templateName);
  emails.render(templateName, { context: context }, function (err, html, text) {
    if (err) {
      error('Error rendering %s template', templateName, err);
      return cb(err);
    }
    log('Rendered template %s, now sending mail', templateName);
    data.html = html;
    data.text = text;
    transporter.sendMail(data, cb);
  });
};
```

It is here where things go awry.  In my logs, I see the line where it indicates

```
Tue, 02 Jun 2015 03:19:56 GMT emg:server:email Rendered template email-report.html, now sending mail
```

So at this point, the template has been rendered and everything is passed on to `nodemailer` to deliver....but that's where I lose it.  **Most of the time** it works, but every once in a while, it just hits this point and never returns.  The callback function passed into `transporter.sendMail(data, cb)` is never called back...ever.  No other errors are logged related to email or anything at all.  It just seems to disappear here and never return.

This is troublesome not only because it isn't working, but it also indicates a memory leak.  I'm also curious why the client embedded in either nodemailer or the sendgrid transport isn't making use of some kind of client-side timeout to eventually return.  It seems like it would -- if you're using standard node http client to hit the sendgrid web api?

I'm not sure what's really going on here without digging more into the source code of this transport and/or nodemailer, but I thought I'd just do a sanity check query here and ask if anyone has seen this behavior before with nodemailer or this transport which uses sendgrid web api?

It is a possibility that [hyperzip](https://github.com/hyperquest/hyperzip) is causing a problem -- I am using that to stream a pdf from Amazon S3 and attach it to the email in gzip format.  I'll have to dig into that more, as well.

Any suggestions welcome.

**Comment by davisford** [comment]
I'm starting to suspect this substack/hyperquest#39

Feel free to close if you think this issue is unrelated to the transport, but if you have any insight, I would love to hear it.

**Comment by eddiezane** [comment]
Hey @davisford,

Sorry for the delay. Did you ever get this sorted out?

**Comment by davisford** [comment]
Yes, I ended up ripping out hyperquest/hyperzip and the problem resolved itself.  There was something going on with one of those libs.
