### ISSUE TITLE
Sending file as an attachment

### ISSUE THREAD

**Issue by JohnAReid** [sendgrid/nodemailer-sendgrid-transport#27]
Could you please give me an example of how to send an attachment as I am getting the error

TypeError: Cannot assign to read only property 'content' of .

**Comment by JohnAReid** [comment]
OK after a few hours finally got it to work!

**Comment by thinkingserious** [comment]
@JohnAReid,

I'm very happy you got it to work! 

But I'm very sad it took hours :(

Could you provide us some feedback on how we could have saved you those hours?

Thanks!

**Comment by JohnAReid** [comment]
It was my fault did not even see the example folder with sample.js in it.  

If you wanted to improve things I would put the attachment line in the readme usage example.

**Comment by thinkingserious** [comment]
@JohnAReid,

We are moving the most common use cases here: https://github.com/sendgrid/sendgrid-nodejs/blob/master/USE_CASES.md and there is now a link in the README Table of Contents. Does that help?

**Comment by JohnAReid** [comment]
@thinkingserious 
SendGrid is working great from me - but I had no idea you could build and run the template from node - I assumed all that was done in the web app!  

It is something I am going to have to get into in a big way as I see emails being the main form of contact with my app's users - but we are only a small team of two and just about to launch so not much free time at the monment.

**Comment by thinkingserious** [comment]
Thats awesome!

We would like to send you and your team mate some T-shirts. Can you email us at dx@sendgrid.com with you and your partner's T-shirt sizes and mailing address? Thanks!
