### ISSUE TITLE
replyTo not working

### ISSUE THREAD

**Issue by iand123** [sendgrid/nodemailer-sendgrid-transport#32]
I am setting replyTo in my code but it doesnt come through on the header

```
replyTo: req.body.contactemail

```
I am validating this on the console and can see it has a value. I am using  "nodemailer-sendgrid-transport": "^0.1.0", according to my package.json

**Comment by thinkingserious** [comment]
Hi @iand123,

This library is not supported by the SendGrid DX team currently. However, this may change at a later date. For now, we recommend you use our [official Node.js SDK](https://github.com/sendgrid/sendgrid-nodejs).

Thanks!

With Best Regards,

Elmer

**Comment by iand123** [comment]
Hi @thinkingserious 

After posting this i found the sdk and migrated my app over to use it. Thanks for the help

**Comment by thinkingserious** [comment]
@iand123,

Thanks for follow up! Welcome to SendGrid!
