### ISSUE TITLE
Add a Code Of Conduct

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/nodemailer-sendgrid-transport#34]
Add a file to the root of this repo called CODE_OF_CONDUCT.md, with the content from the [same file in our docs repo](https://github.com/sendgrid/docs/pull/3048).

**Comment by DanielCBrooks** [comment]
I'll pick this up!

**Comment by mbernier** [comment]
Nice @DanielCBrooks

**Comment by DanielCBrooks** [comment]
Pull request is here:
https://github.com/sendgrid/nodemailer-sendgrid-transport/pull/35
