### ISSUE TITLE
Add a .codeclimate.yml file to this repo

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/nodemailer-sendgrid-transport#48]
It is possible to configure how CodeClimate looks at a repository.
[These Docs](https://docs.codeclimate.com/docs/getting-started-configuration) explain how this is done. Please create an appropriate .codeclimate.yml for this repo. It should test the main language of the repo and run tests.

**Comment by deanbrophy** [comment]
Hello,
I created a PR with the default outputs of Codeclimate's CLI init function. I removed the extraneous languages from the file, but it also created two eslint files. Let me know if those should be removed as well. Thanks!
