### ISSUE TITLE
update year in license.txt

### ISSUE THREAD

**Issue by rahulkumaran** [sendgrid/nodemailer-sendgrid-transport#68]
Currently, it says 2016-2017. Needs to be changed to 2018. Would like to update this myself.

**Comment by thinkingserious** [comment]
This repo is no longer supported, the code base is being moved [here](https://github.com/sendgrid/sendgrid-nodejs/pull/707).

I hope you will make contributions there in support of [Hacktoberfest](https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/) :)
